apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "parserod.fullname" . }}-web
  labels:
    {{- include "parserod.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  {{- if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.web.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "parserod.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "parserod.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ include "parserod.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          image: {{ include "parserod.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: ROLE
              value: "web"
            - name: WORKER_COUNT
              value: {{ .Values.web.workerCount | quote }}
            {{- with .Values.config.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "parserod.fullname" . }}-config
            - secretRef:
                name: {{ include "parserod.secretName" . }}
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
